export interface ElectionDTO {
    id: number,
    descriptionBlob: string,
    descriptionIpfsCid: string,
    authorizedVoterCount: number,
    privateKey: string | null,
    publicKey: string,
    registerPublicKeyE: string,
    registerPublicKeyN: string,
    registeredVoterCount: number,
    registrationEndTime: number,
    registrationStartTime: number,
    status: number,
    totalVotes: number,
    transactionHash: string,
    votingEndTime: number,
    votingStartTime: number,
}